// Shared RBAC types — safe to import from both server and client components.

export type Permission =
  | 'org:update'
  | 'org:delete'
  | 'billing:manage'
  | 'onboarding:view'
  | 'onboarding:create'
  | 'onboarding:update'
  | 'onboarding:delete'
  | 'onboarding:share'
  | 'members:invite'
  | 'members:remove'
  | 'members:update_role'
  | 'members:view'
  | 'projects:create'
  | 'projects:update'
  | 'projects:delete'
  | 'projects:view'
  | 'inventory:create'
  | 'inventory:update'
  | 'inventory:delete'
  | 'inventory:view'
  | 'settings:manage'
  | 'settings:view'
  | 'analytics:view'
  | 'sales:view'
  | 'marketing:view'
  | 'marketing:create'
  | 'marketing:update'
  | 'marketing:delete'
  | 'invoices:view'
  | 'invoices:create'
  | 'invoices:update'
  | 'invoices:delete';

export type OrgRole = 'superadmin' | 'admin' | 'member';

export type MemberStatus = 'active' | 'suspended';

export type AuditAction =
  | 'org.created'
  | 'org.updated'
  | 'org.deleted'
  | 'onboarding.client_created'
  | 'onboarding.client_updated'
  | 'onboarding.client_deleted'
  | 'onboarding.contract_drafted'
  | 'onboarding.contract_deleted'
  | 'onboarding.project_assigned'
  | 'onboarding.share_link_created'
  | 'onboarding.step_updated'
  | 'member.invited'
  | 'member.removed'
  | 'member.role_changed'
  | 'member.status_changed'
  | 'project.created'
  | 'project.updated'
  | 'project.deleted'
  | 'settings.updated'
  | 'billing.subscription_changed'
  | 'billing.stripe_connected'
  | 'billing.stripe_disconnected'
  | 'billing.stripe_onboarding_retry'
  | 'billing.provider_connected'
  | 'billing.provider_disconnected'
  | 'billing.default_provider_changed'
  | 'connections.listing_connected'
  | 'connections.listing_disconnected'
  | 'connections.listing_default_changed'
  | 'connections.document_connected'
  | 'connections.document_disconnected'
  | 'connections.document_default_changed'
  | 'inventory.created'
  | 'inventory.updated'
  | 'inventory.deleted'
  | 'marketing.created'
  | 'marketing.updated'
  | 'marketing.deleted'
  | 'invoice.created'
  | 'invoice.updated'
  | 'invoice.deleted';
