-- Migration: Allow direct browser uploads to inventory-images via signed URLs.
--
-- The prepare/finalize server actions generate short-lived signed upload URLs
-- using the service-role key. The browser then PUTs directly to that signed URL.
-- No broad INSERT policy is needed on storage.objects because signed URLs
-- bypass RLS. We only need a public SELECT policy so getPublicUrl works for
-- rendering thumbnails/medium images.

-- Ensure the bucket exists and is public (for read access to processed images).
insert into storage.buckets (id, name, public)
values ('inventory-images', 'inventory-images', true)
on conflict (id) do update set public = true;

-- Allow anyone to read (download) objects from inventory-images.
-- This is safe because the bucket only contains processed estate-sale item images.
create policy "Public read access for inventory images"
  on storage.objects for select
  using (bucket_id = 'inventory-images');

-- Allow the service role (used by server actions & queue workers) full access.
-- Signed upload URLs generated by the service-role client already bypass RLS,
-- so this policy is a safety net for server-side operations like processItemImage.
create policy "Service role full access for inventory images"
  on storage.objects
  for all
  using (bucket_id = 'inventory-images' and auth.role() = 'service_role')
  with check (bucket_id = 'inventory-images' and auth.role() = 'service_role');
